# https://github.com/compose-spec/compose-spec/blob/master/spec.md
services:
  nfs-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "nfs-server"
    volumes:
      - ./../data:/nfs-mount
      # - ./../data:/nfs-mount:ro
    restart: always
    privileged: true
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
